
# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/Dockerfile to edit this template

FROM quay.io/wildfly/wildfly-centos7
ADD target/mavenproject2-1.0-SNAPSHOT.war /opt/wildfly/standalone/deployments/


    